# Note: Parameters can be hardcoded directly in 'deploy-functions.yaml'
# if you do not need to vary them between your functions!
# Forced the github to run even in case of oee changes
description: "Function to calculate OEE"
owner: CDF Bootcamp Team
cpu: 1.0
memory: 1.5
data_set_id: 4658547319924942
